spring:
      application:
        name: config-Server
      cloud:
        config:
          uri:
          
server:
  port: 8889
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8081/eureka
