spring:
  application:
    name: cloud-model-user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization: true
server:
  port: 8003

info:
  app:
    name: ${spring.application.name}
    address: ${spring.cloud.client.ipAddress}:${server.port}


management:
  security:
    enabled: false




